/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.decorator.view;

import com.decorator.model.Arroz;
import com.decorator.model.Basica;
import com.decorator.model.Carne;
import com.decorator.model.Completa;
import com.decorator.model.Farofa;
import com.decorator.model.Janta;
import com.decorator.model.Mandioca;
import com.decorator.model.Tropeiro;
import com.decorator.model.Vinagrete;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author tiago
 */
public class Tela extends javax.swing.JFrame {
    ArrayList<String> listaDeCondimentos = new ArrayList<>();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxTipoJanta = new javax.swing.JComboBox<>();
        Farofa = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Arroz = new javax.swing.JRadioButton();
        Carne = new javax.swing.JRadioButton();
        Vinagrete = new javax.swing.JRadioButton();
        Mandioca = new javax.swing.JRadioButton();
        Tropeiro = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxTipoJanta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completa", "Basica" }));

        Farofa.setText("Farofa");
        Farofa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FarofaActionPerformed(evt);
            }
        });

        jLabel1.setText("Adicionais:");

        Arroz.setText("Arroz");
        Arroz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrozActionPerformed(evt);
            }
        });

        Carne.setText("Carne");
        Carne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarneActionPerformed(evt);
            }
        });

        Vinagrete.setText("Vinagrete");
        Vinagrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VinagreteActionPerformed(evt);
            }
        });

        Mandioca.setText("Mandioca");
        Mandioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MandiocaActionPerformed(evt);
            }
        });

        Tropeiro.setText("Tropeiro");
        Tropeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TropeiroActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxTipoJanta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Tropeiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Vinagrete)))
                                .addGap(1, 1, 1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Arroz)
                                    .addComponent(Farofa))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mandioca)
                                    .addComponent(Carne))))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTipoJanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Arroz)
                        .addComponent(Carne)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Farofa)
                    .addComponent(Mandioca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tropeiro)
                    .addComponent(Vinagrete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FarofaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FarofaActionPerformed
        if(listaDeCondimentos.isEmpty()){
        listaDeCondimentos.add(Farofa.getText());
        }
        else{
            
            if(listaDeCondimentos.contains(Farofa.getText())){
               listaDeCondimentos.remove(Farofa.getText());
            }else{
                listaDeCondimentos.add(Farofa.getText());
            }
        }
        
    }//GEN-LAST:event_FarofaActionPerformed

    private void ArrozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrozActionPerformed
        if(listaDeCondimentos.isEmpty()){
        listaDeCondimentos.add(Arroz.getText());
        }
        else{
            if(listaDeCondimentos.contains(Arroz.getText())){
               listaDeCondimentos.remove(Arroz.getText());
            }else{
                listaDeCondimentos.add(Arroz.getText());
            }
        }
    }//GEN-LAST:event_ArrozActionPerformed

    private void CarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarneActionPerformed
        if(listaDeCondimentos.isEmpty()){
        listaDeCondimentos.add(Carne.getText());
        }
        else{
            if(listaDeCondimentos.contains(Carne.getText())){
               listaDeCondimentos.remove(Carne.getText());
            }else{
                listaDeCondimentos.add(Carne.getText());
            }
        }
    }//GEN-LAST:event_CarneActionPerformed

    private void VinagreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VinagreteActionPerformed
        if(listaDeCondimentos.isEmpty()){
        listaDeCondimentos.add(Vinagrete.getText());
        }
        else{
            if(listaDeCondimentos.contains(Vinagrete.getText())){
               listaDeCondimentos.remove(Vinagrete.getText());
            }else{
                listaDeCondimentos.add(Vinagrete.getText());
            }
        }
    }//GEN-LAST:event_VinagreteActionPerformed

    private void MandiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MandiocaActionPerformed
        if(listaDeCondimentos.isEmpty()){
        listaDeCondimentos.add(Mandioca.getText());
        }
        else{
            if(listaDeCondimentos.contains(Mandioca.getText())){
               listaDeCondimentos.remove(Mandioca.getText());
            }else{
                listaDeCondimentos.add(Mandioca.getText());
            }
        }
    }//GEN-LAST:event_MandiocaActionPerformed

    private void TropeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TropeiroActionPerformed
       if(listaDeCondimentos.isEmpty()){
        listaDeCondimentos.add(Tropeiro.getText());
        }
        else{
            if(listaDeCondimentos.contains(Tropeiro.getText())){
               listaDeCondimentos.remove(Tropeiro.getText());
            }else{
                listaDeCondimentos.add(Tropeiro.getText());
            }
        }
    }//GEN-LAST:event_TropeiroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jComboBoxTipoJanta.getSelectedIndex() == 0){
            Janta janta = new Completa();
            for(String condimento : listaDeCondimentos){
                System.out.println(condimento);
            switch (condimento.toLowerCase()) {
            case "farofa": janta = new Farofa(janta); break;
            case "arroz": janta = new Arroz(janta);break;
            case "carne":janta = new Carne(janta);break;
            case "tropeiro":janta = new Tropeiro(janta);break;
            case "vinagrete":janta = new Vinagrete(janta);break;
            case "mandioca":janta = new Mandioca(janta);break;            
           }
        }
        jTextArea1.setText(String.valueOf(janta.preco()));
        }else{
           Janta janta = new Basica();
            for(String condimento : listaDeCondimentos){
                System.out.println(condimento);
            switch (condimento.toLowerCase()) {
            case "farofa": janta = new Farofa(janta); break;
            case "arroz": janta = new Arroz(janta);break;
            case "carne":janta = new Carne(janta);break;
            case "tropeiro":janta = new Tropeiro(janta);break;
            case "vinagrete":janta = new Vinagrete(janta);break;
            case "mandioca":janta = new Mandioca(janta);break;            
           }
        }           jTextArea1.setText(String.valueOf(janta.preco()));  
        }              
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Arroz;
    private javax.swing.JRadioButton Carne;
    private javax.swing.JRadioButton Farofa;
    private javax.swing.JRadioButton Mandioca;
    private javax.swing.JRadioButton Tropeiro;
    private javax.swing.JRadioButton Vinagrete;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxTipoJanta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
